DROP SEQUENCE serial;

DROP FUNCTION id_insert();

DROP TRIGGER make_id_1 ON t_user ;

DROP TRIGGER make_id_2 ON APP_ALARM ;

DROP TRIGGER make_id_3 ON APP_ALARM_FEEDBACK ;

DROP TRIGGER make_id_4 ON DUTY_RECORD ;

DROP TRIGGER make_id_5 ON GIS_LOG ;

DROP TRIGGER make_id_6 ON LOCAL_TRACK ;

DROP TRIGGER make_id_7 ON SET_ALARMDEV ;

DROP TRIGGER make_id_8 ON SET_ALARM_FILTER ;

DROP TRIGGER make_id_9 ON SET_ALARM_LINE_ORDER ;

DROP TRIGGER make_id_10 ON SET_LED ;

DROP TRIGGER make_id_11 ON SET_VOICE ;

DROP TRIGGER make_id_12 ON STATION_KAKO ;

DROP TRIGGER make_id_13 ON STATION_POLICE ;

DROP TRIGGER make_id_14 ON STATION_TICKLANE ;

DROP TRIGGER make_id_15 ON SYS_LOG ;

DROP TRIGGER make_id_16 ON T_CODE ;

DROP TRIGGER make_id_17 ON T_ORG ;

DROP TRIGGER make_id_18 ON VIDEO_CRUISE ;

DROP TRIGGER make_id_19 ON VIDEO_CRUISE_ORDER ;

DROP TRIGGER make_id_20 ON T_AUTH ;

DROP TRIGGER make_id_21 ON T_ROLE ;

CREATE SEQUENCE serial START 100000000000000000;

CREATE OR REPLACE FUNCTION id_insert() RETURNS trigger AS $BODY$    
BEGIN     
    NEW.id := nextval('serial');    
    RETURN NEW;   
END;      
$BODY$    
  LANGUAGE 'plpgsql';

CREATE TRIGGER make_id_1   
	BEFORE INSERT ON t_user    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert(); 
	
CREATE TRIGGER make_id_2   
	BEFORE INSERT ON APP_ALARM    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_3   
	BEFORE INSERT ON APP_ALARM_FEEDBACK    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_4   
	BEFORE INSERT ON DUTY_RECORD    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_5   
	BEFORE INSERT ON GIS_LOG    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_6   
	BEFORE INSERT ON LOCAL_TRACK    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_7   
	BEFORE INSERT ON SET_ALARMDEV    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_8   
	BEFORE INSERT ON SET_ALARM_FILTER    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_9   
	BEFORE INSERT ON SET_ALARM_LINE_ORDER    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_10   
	BEFORE INSERT ON SET_LED    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_11   
	BEFORE INSERT ON SET_VOICE    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_12   
	BEFORE INSERT ON STATION_KAKO    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_13   
	BEFORE INSERT ON STATION_POLICE    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_14   
	BEFORE INSERT ON STATION_TICKLANE    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_15   
	BEFORE INSERT ON SYS_LOG    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_16   
	BEFORE INSERT ON T_CODE    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_17   
	BEFORE INSERT ON T_ORG    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_18   
	BEFORE INSERT ON VIDEO_CRUISE    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_19   
	BEFORE INSERT ON VIDEO_CRUISE_ORDER    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_20   
	BEFORE INSERT ON T_AUTH    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();
	
CREATE TRIGGER make_id_21   
	BEFORE INSERT ON T_ROLE    
	FOR EACH ROW           
	EXECUTE PROCEDURE id_insert();